# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER kangaroo

# 挂载目录
VOLUME /home/kangaroo
# 创建目录
RUN mkdir -p /home/kangaroo
# 指定路径
WORKDIR /home/kangaroo
# 复制jar文件到路径
COPY ./jar/kangaroo-gateway.jar /home/kangaroo/kangaroo-gateway.jar
# 启动网关服务
ENTRYPOINT ["java","-jar","kangaroo-gateway.jar"]