package ink.kangaroo.wms.model;

/**
 * @author kbw
 * @version 1.0
 * @date 2021/9/3 18:27
 */
public class Module {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.id
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.name
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.description
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.level
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Byte level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.rootId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer rootId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.parentId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.created
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.updated
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.isShow
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.isDeleted
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.userId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.css
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String css;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Module.js
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String js;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.id
     *
     * @return the value of Module.id
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.id
     *
     * @param id the value for Module.id
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.name
     *
     * @return the value of Module.name
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.name
     *
     * @param name the value for Module.name
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.description
     *
     * @return the value of Module.description
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.description
     *
     * @param description the value for Module.description
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.level
     *
     * @return the value of Module.level
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.level
     *
     * @param level the value for Module.level
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.rootId
     *
     * @return the value of Module.rootId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getRootId() {
        return rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.rootId
     *
     * @param rootId the value for Module.rootId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setRootId(Integer rootId) {
        this.rootId = rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.parentId
     *
     * @return the value of Module.parentId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.parentId
     *
     * @param parentId the value for Module.parentId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.created
     *
     * @return the value of Module.created
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.created
     *
     * @param created the value for Module.created
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.updated
     *
     * @return the value of Module.updated
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.updated
     *
     * @param updated the value for Module.updated
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.isShow
     *
     * @return the value of Module.isShow
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.isShow
     *
     * @param isShow the value for Module.isShow
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.isDeleted
     *
     * @return the value of Module.isDeleted
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.isDeleted
     *
     * @param isDeleted the value for Module.isDeleted
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.userId
     *
     * @return the value of Module.userId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.userId
     *
     * @param userId the value for Module.userId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.css
     *
     * @return the value of Module.css
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getCss() {
        return css;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.css
     *
     * @param css the value for Module.css
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setCss(String css) {
        this.css = css == null ? null : css.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Module.js
     *
     * @return the value of Module.js
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getJs() {
        return js;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Module.js
     *
     * @param js the value for Module.js
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setJs(String js) {
        this.js = js == null ? null : js.trim();
    }
}
