package ink.kangaroo.wms.model;

import cn.org.atool.fluent.mybatis.annotation.FluentMybatis;
import cn.org.atool.fluent.mybatis.base.IEntity;
import lombok.Data;

/**
 * @author kbw
 * @version 1.0
 * @date 2021/9/3 18:26
 */
@Data
@FluentMybatis
public class TemplateDef  implements IEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.id
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.moduleId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer moduleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.name
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.created
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.updated
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.userId
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.isDeleted
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateDef.structure
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String structure;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.id
     *
     * @return the value of TemplateDef.id
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.id
     *
     * @param id the value for TemplateDef.id
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.moduleId
     *
     * @return the value of TemplateDef.moduleId
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.moduleId
     *
     * @param moduleId the value for TemplateDef.moduleId
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.name
     *
     * @return the value of TemplateDef.name
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.name
     *
     * @param name the value for TemplateDef.name
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.created
     *
     * @return the value of TemplateDef.created
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.created
     *
     * @param created the value for TemplateDef.created
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.updated
     *
     * @return the value of TemplateDef.updated
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.updated
     *
     * @param updated the value for TemplateDef.updated
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setUpdated(Integer updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.userId
     *
     * @return the value of TemplateDef.userId
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.userId
     *
     * @param userId the value for TemplateDef.userId
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.isDeleted
     *
     * @return the value of TemplateDef.isDeleted
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.isDeleted
     *
     * @param isDeleted the value for TemplateDef.isDeleted
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateDef.structure
     *
     * @return the value of TemplateDef.structure
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getStructure() {
        return structure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateDef.structure
     *
     * @param structure the value for TemplateDef.structure
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setStructure(String structure) {
        this.structure = structure == null ? null : structure.trim();
    }
}
