package ink.kangaroo.wms.model;

public class TemplateDataWithBLOBs extends TemplateData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateData.data
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateData.htmlText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String htmlText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateData.data
     *
     * @return the value of TemplateData.data
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateData.data
     *
     * @param data the value for TemplateData.data
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateData.htmlText
     *
     * @return the value of TemplateData.htmlText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getHtmlText() {
        return htmlText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateData.htmlText
     *
     * @param htmlText the value for TemplateData.htmlText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setHtmlText(String htmlText) {
        this.htmlText = htmlText == null ? null : htmlText.trim();
    }
}