package ink.kangaroo.wms.model;

public class TemplateInstanceWithBLOBs extends TemplateInstance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateInstance.jsText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String jsText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TemplateInstance.phpText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    private String phpText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateInstance.jsText
     *
     * @return the value of TemplateInstance.jsText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getJsText() {
        return jsText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateInstance.jsText
     *
     * @param jsText the value for TemplateInstance.jsText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setJsText(String jsText) {
        this.jsText = jsText == null ? null : jsText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TemplateInstance.phpText
     *
     * @return the value of TemplateInstance.phpText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public String getPhpText() {
        return phpText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TemplateInstance.phpText
     *
     * @param phpText the value for TemplateInstance.phpText
     *
     * @mbggenerated Mon Jan 04 13:23:33 CST 2016
     */
    public void setPhpText(String phpText) {
        this.phpText = phpText == null ? null : phpText.trim();
    }
}