apiVersion: v1
kind: PersistentVolume
metadata:
  name: kangaroo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/docker/data/nfs/kangaroo
    server: 192.168.1.119